# Judge0 configuration file
# For full list of configuration options see: https://github.com/judge0/judge0/blob/master/judge0.conf

# To use this configuration file, mount it into the container and pass `--config` flag to the process.
# E.g.: docker run -v /path/to/judge0.conf:/judge0.conf judge0/judge0:latest --config /judge0.conf

REDIS_URL=redis://redis:6379/0
REDIS_PASSWORD=

POSTGRES_HOST=db
POSTGRES_PORT=5432
POSTGRES_DB=judge0
POSTGRES_USER=judge0
POSTGRES_PASSWORD=judge0_password

# Authentication (Disable for local dev)
AUTH_CALLBACK_TOKEN=
AUTH_TOKEN=
ENABLE_WAIT_RESULT=true

# Workers
MAX_QUEUE_SIZE=100
MAX_CONCURRENT_WORKERS=2
